### ISSUE TITLE
1.21.1 version

### ISSUE THREAD

**Issue by I-Want-Ninja** [DevDyna/RecipeBlender#14]
### Core Section

- [X] I have searched on opened issues of this repository

### Description

Neoforge

hello i installed it on atm10 newest  the recepies show up but i cant autocraft with the stone cutter with ae2 i put a pattern provider below the cutter and it dosnt work    
also a new crafting recepie was added with modern industrialization  bronze cutting machine  it works with this machine but stone cutting part dosnt

**Comment by DevDyna** [comment]
> i put a pattern provider below the cutter and it dosnt work

this isn't a bug related chipped-express but a wrong placement of pattern provider : [[ae2 online guide](https://guide.appliedenergistics.org/1.21/items-blocks-machines/patterns#root)]

![image](https://github.com/user-attachments/assets/ed3babd4-9aa7-48ce-b282-a42c4952d188)
